### ISSUE TITLE
Yaml parser does not handle Windows CRLF correctly

### ISSUE THREAD

**Issue by jfbilodeau** [korlibs/korge-next#351]
It seems that the Yaml parser fail to properly read a yaml file on Windows. For example:
```yaml
key1:
  read: true
key2:
  read: false
```
`key` is read but `key2` is never read. Switching the file to LF (or running on a real OS) solves the problem.
