### ISSUE TITLE
Issues with sonatype/maven central releasing

### ISSUE THREAD

**Issue by soywiz** [korlibs/korge-next#654]
It seems that concurrency makes some file artifacts to be published in different repositories, and that might lead to the release failing. We can reduce concurrency to 1 in the deploy workflow for now. But we should probably create a specific repository.

https://support.sonatype.com/hc/en-us/articles/213465448-Automatically-dropping-old-staging-repositories

**Comment by soywiz-invideo** [comment]
We should probably create a stagedRepositoryId in an initial job:

https://support.sonatype.com/hc/en-us/articles/213465868-Uploading-to-a-Staging-Repository-via-REST-API

Then use that id and pass it as outputs for each machine:

```
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
    - id: step1
      run: echo "::set-output name=test::hello"
    - id: step2
      run: echo "::set-output name=test::world"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
```

Also note that now the macOS target can build all the other targets, so maybe we can do this in a single job.
But it is important to create the staging repository, because if not, it creates temporary staging repositories when doing multithreading, and that might lead to uploading artifacts partially that missing other files that cannot be committed atomically and thus it will fail.
